name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your main branch if necessary

permissions:
  contents: write # Grant write access to the contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Clear gh-pages cache
        run: rm -rf node_modules/.cache/gh-pages

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the provided token for authentication
